# -*- coding: utf-8 -*-
"""VOTING ELIGIBILITY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q9oNOKfnhYftibI1qpmqHrtEDpMuVXQj
"""

print("Voting eligibility")
age=int(input("enter your age:\n"))
if age>=18:
    print("eligible to vote.")
else:
    print("not eligible to vote.")

